In [1]:
import pandas as pd

df = pd.read_csv('/content/dataset_vendas.csv')

#Diagnóstico do Dataset

In [ ]:
# visualizando as 5 primeiras linhas

df.head()

,data,produto,cliente,regiao,quantidade,preco_unitario,categoria,faturamento
0,2023-01-02,Monitor,Cliente_24,Centro-Oeste,4,2298.63,Eletrônicos,9194.52
1,2023-01-05,Monitor,Cliente_24,Sudeste,2,3785.44,Eletrônicos,7570.88
2,2023-01-09,Notebook,Cliente_26,Centro-Oeste,3,3430.76,Eletrônicos,10292.28
3,2023-01-13,Tablet,Cliente_41,Nordeste,3,4563.67,Eletrônicos,13691.01
4,2023-01-14,Notebook,Cliente_10,Sudeste,2,4841.57,Eletrônicos,9683.14

In [ ]:
# visualizando as informações do dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   data            200 non-null    object
 1   produto         200 non-null    object
 2   cliente         200 non-null    object
 3   regiao          200 non-null    object
 4   quantidade      200 non-null    int64
 5   preco_unitario  200 non-null    float64
 6   categoria       200 non-null    object
 7   faturamento     200 non-null    float64
dtypes: float64(2), int64(1), object(5)
memory usage: 12.6+ KB

In [ ]:
# Verificando se há valores nulos

df.isnull().sum()

data              0
produto           0
cliente           0
regiao            0
quantidade        0
preco_unitario    0
categoria         0
faturamento       0
dtype: int64

In [10]:
# verificando se há outliers

numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns

if not numeric_cols.empty:
    Q1 = df[numeric_cols].quantile(0.25)
    Q3 = df[numeric_cols].quantile(0.75)
    IQR = Q3 - Q1

    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR

    outliers = []

    for col in numeric_cols:
        df = df[(df[col] >= limite_inferior[col]) & (df[col] <= limite_superior[col])]

    print("Outliers encontrados:", outliers)
    print("Quantidade de outliers:", len(outliers))
else:
    print("Nenhuma coluna numérica encontrada para tratamento de outliers.")

Outliers encontrados: []
Quantidade de outliers: 0

# Tratamento dos dados

In [ ]:
# removendo duplicados

df.drop_duplicates(inplace=True)

In [ ]:
# criação da coluna mês
df['data'] = pd.to_datetime(df['data'])
df['mes'] = df['data'].dt.month

In [ ]:
# criação da coluna ticket médio

df['ticket_medio'] = df['faturamento'] / df['quantidade']

In [ ]:
# visualizando valores estatísticos

df.describe()

,data,quantidade,preco_unitario,faturamento,mes,ticket_medio
count,200,200.000000,200.000000,200.000000,200.000000,200.000000
mean,2023-07-07 23:09:36,2.460000,2568.173900,6430.882400,6.735000,2568.173900
min,2023-01-02 00:00:00,1.000000,63.420000,63.420000,1.000000,63.420000
25%,2023-04-09 18:00:00,2.000000,1307.640000,2405.667500,4.000000,1307.640000
50%,2023-07-10 12:00:00,2.000000,2702.745000,5945.710000,7.000000,2702.745000
75%,2023-09-28 18:00:00,3.000000,3723.682500,9274.380000,9.250000,3723.682500
max,2023-12-30 00:00:00,4.000000,4988.580000,19820.400000,12.000000,4988.580000
std,NaN,1.060198,1384.952361,4549.435653,3.421007,1384.952361

#Carregamento dos dados

In [ ]:
# salvando as alterações em csv

df.to_csv('dataset_vendas_tratado.csv', index=False)